language: python

branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.6
      env: TOXENV=mypy

install:
- pip install -U tox codecov

script: tox

after_success:
- codecov

deploy:
  provider: pypi
  user: "__token__"
  distributions: "sdist bdist_wheel"
  password:
    secure: "HICo1Ck7QQXO8Ihh/XVNwz6eU2xbi0lHWqZLKGrLcaYL08ChyDXg03TPi2ICFr7Olv3GECuNhoCNxMvuOAQwXyXUO2xqQSdKqfjFqn3lJKk9MFblat3B0q0qTDLB0O0SZcq7Pc1tMhMAucubc2g343m/5bAzZZKb9kw0GFMJD35mDnh1NDagNnH9isuvSogjuF5HQt/J+pTXDZ3326joiLjuTd4Ar6kFFRqyRdu30fr7/RugaKTAl+eunxAZ4ZzMcr2BwGqENBPU21uPZ7n0byPsLjZWzfoUFL/JxOMYNhbLuSGl6LyvNfvtRKsdMw81NeqjtqZ1UcD9Q2MG+N0WbuYzMspqBgyrCGW+D430DWK7Vr7AiDSjVtLK8I7qsut6Pxx4J4wZvBCZHRd4spHe+ky5a4dxKuqpONw9EHhIt7hA26gwkHJ6X0Y6DisCw/7w4fICNzlZLBTI0S05gY2e/YoD2RpDJtk+IZNZCZvjoT6SO0rrqID0nTFkxVz06UeQQ+IZNyRdqcVWOCtorxXtB9LoxJxeUP4jNIj8Hsrd1DWVhFz6UkRGX8oT84mqSEM3moySauB2XRI6g8e1nlOSdXElr/AAXfEhhnEJHnspRvCkk7k9mgAERnNcuFQoyMLC/XFwjTH2m0qD4ratVPeKqZp8FlQvYKhCvGObTvlApos="
  on:
    tags: true
    repo: scrapinghub/scrapinghub-autoextract
    condition: $TOXENV == py37
